version: '3.7'
services:
  zoo:
    image: confluentinc/cp-zookeeper:7.5.1
    hostname: zoo
    ports:
      - "2181:2181"
    container_name: zoo
    networks: 
      - kafkapp_network
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka1:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka1
    container_name: kafka1
    networks: 
      - kafkapp_network
    ports:
      - "9092:9092"
    depends_on:
      - zoo
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_LISTENER: PLAINTEXT_DOCKER://kafka1:29092,PLAINTEXT_HOST://192.168.10.108:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_DOCKER://kafka1:29092,PLAINTEXT_HOST://192.168.10.108:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_DOCKER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_DOCKER

  kafka2:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka2
    container_name: kafka2
    networks: 
      - kafkapp_network
    ports:
      - "9093:9093"
    depends_on:
      - zoo
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_LISTENER: PLAINTEXT_DOCKER://kafka2:29093,PLAINTEXT_HOST://192.168.10.108:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_DOCKER://kafka2:29093,PLAINTEXT_HOST://192.168.10.108:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_DOCKER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_DOCKER
    
  kafka3:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka3
    container_name: kafka3
    networks: 
      - kafkapp_network
    ports:
      - "9094:9094"
    depends_on:
      - zoo
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_LISTENER: PLAINTEXT_DOCKER://kafka3:29094,PLAINTEXT_HOST://192.168.10.108:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_DOCKER://kafka3:29094,PLAINTEXT_HOST://192.168.10.108:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_DOCKER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_DOCKER

  kafka-ui:
    image: provectuslabs/kafka-ui
    hostname: kafka-ui
    container_name: kafka-ui
    networks: 
      - kafkapp_network
    ports:
      - "8080:8080"
    depends_on:
      - zoo
      - kafka1
      - kafka2
      - kafka3
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'

networks:
  kafkapp_network:
    driver: bridge