server:
  port : 8081

spring:
    profiles:
        active: local
    kafka:
        topic: "library-events"
        producer:
            bootstrap-servers: 192.168.10.108:9092,192.168.10.108:9093,192.168.10.108:9094
            key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        admin:
            properties:
                bootstrap-servers: 192.168.10.108:9092,192.168.10.108:9093,192.168.10.108:9094
